//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ChildPackage
    {
        public int ID { get; set; }
        public int PId { get; set; }
        public byte[] UpdateFlag { get; set; }
        public string Name { get; set; }
        public System.DateTime InitTime { get; set; }
        public double PersonalPrice { get; set; }
        public double GroupPrice { get; set; }
        public Nullable<System.DateTime> TimeAmount { get; set; }
        public Nullable<int> TimeDay { get; set; }
        public int Status { get; set; }
        public string Version { get; set; }
        public string Memo { get; set; }
        public string PlateStr { get; set; }
    }
}
