//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ErrorInfo
    {
        public int ID { get; set; }
        public int questionID { get; set; }
        public Nullable<int> qType { get; set; }
        public int errorTagID { get; set; }
        public int redoCount { get; set; }
        public Nullable<int> packageId { get; set; }
        public int stageID { get; set; }
        public Nullable<int> plateType { get; set; }
        public string answer { get; set; }
        public int userID { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public string errorContent { get; set; }
        public Nullable<int> groupID { get; set; }
        public Nullable<int> taskId { get; set; }
    }
}
