//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PaperQuestionScore
    {
        public int ID { get; set; }
        public int PaperID { get; set; }
        public int QuestionType { get; set; }
        public double Score { get; set; }
        public string Name { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> isadd { get; set; }
    }
}
