//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PaperSchemaQuestiontype
    {
        public int ID { get; set; }
        public byte[] UpdateFlag { get; set; }
        public int SID { get; set; }
        public int QuesionBaseTypeID { get; set; }
        public string QuestionTypeShowName { get; set; }
        public int Num { get; set; }
        public double Score { get; set; }
        public Nullable<int> Sort { get; set; }
    }
}
