//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PaperSchemaManualRegulation
    {
        public int ID { get; set; }
        public byte[] UpdateFlag { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> QuestionType { get; set; }
        public string KId { get; set; }
        public string KName { get; set; }
        public Nullable<int> Dif { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<int> SId { get; set; }
    }
}
