//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Plate
    {
        public int ID { get; set; }
        public byte[] UpdateFlag { get; set; }
        public int Type { get; set; }
        public string Name { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> CID { get; set; }
        public string desc { get; set; }
        public Nullable<bool> isSort { get; set; }
        public Nullable<int> ErrorCount { get; set; }
        public Nullable<int> layout { get; set; }
        public string ico { get; set; }
    }
}
