//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TaskProcessDetail
    {
        public int ID { get; set; }
        public Nullable<int> stageID { get; set; }
        public int StructureID { get; set; }
        public Nullable<int> taskId { get; set; }
        public Nullable<int> courseId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> timeSpan { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
    }
}
