//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Taskold
    {
        public int ID { get; set; }
        public byte[] UpdateFlag { get; set; }
        public string Content { get; set; }
        public int Sort { get; set; }
        public int Types { get; set; }
        public int IsFree { get; set; }
        public Nullable<bool> IsBd { get; set; }
        public Nullable<int> Bounds { get; set; }
        public Nullable<int> Scores { get; set; }
        public Nullable<int> Isrules { get; set; }
        public string Title { get; set; }
        public string QuestionDesc { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
    }
}
