//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_User_copy2
    {
        public long ID { get; set; }
        public byte[] UpdateFlag { get; set; }
        public int AppId { get; set; }
        public int AdminId { get; set; }
        public string Code { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public byte[] FaceImageData { get; set; }
        public Nullable<int> UserStatus { get; set; }
        public Nullable<int> CountLogin { get; set; }
        public string LastLoginIp { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int UserType { get; set; }
        public string ClassName { get; set; }
        public Nullable<short> Sex { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Gold { get; set; }
        public string Mobile { get; set; }
        public Nullable<bool> IsMobileValid { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsEmailValid { get; set; }
        public string QQ { get; set; }
        public string QQId { get; set; }
        public string IdCard { get; set; }
        public string Signature { get; set; }
        public string Memo { get; set; }
        public string DeviceSerialNo { get; set; }
        public string NickName { get; set; }
        public Nullable<System.DateTime> InitTime { get; set; }
        public string imgurl { get; set; }
        public string Birthday { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public Nullable<int> examtype { get; set; }
        public Nullable<int> learntype { get; set; }
        public Nullable<int> learnfont { get; set; }
        public Nullable<int> removeError { get; set; }
        public string examdate { get; set; }
    }
}
