//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_UserOrders
    {
        public int Id { get; set; }
        public byte[] UpdateFlag { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> InitTime { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public int Count { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<short> IsPay { get; set; }
        public string PayTypeCode { get; set; }
        public string TradeNo { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Memo { get; set; }
        public Nullable<int> VirtualCoin { get; set; }
        public Nullable<double> totalPrice { get; set; }
        public Nullable<int> discountId { get; set; }
        public Nullable<int> couponid { get; set; }
        public Nullable<int> appid { get; set; }
        public string useCoupon { get; set; }
        public Nullable<double> discountMoney { get; set; }
    }
}
