//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_VirtualMoneyDetails
    {
        public int Id { get; set; }
        public byte[] UpdateFlag { get; set; }
        public Nullable<System.DateTime> InitTime { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Moblie { get; set; }
        public string PayTypeCode { get; set; }
        public Nullable<decimal> VirtualMoney { get; set; }
        public Nullable<System.DateTime> PayDateTime { get; set; }
        public string Description { get; set; }
        public Nullable<int> OperatorUserId { get; set; }
        public string OperatorUserName { get; set; }
        public string TradeNo { get; set; }
        public string OrderNumber { get; set; }
    }
}
